### ISSUE TITLE
JOSS submission skeleton

### ISSUE THREAD

**Issue by jbytecode** [SevgiAkten/pycellga#16]
JOSS requires a paper folder that holds two main file, the first one is for the manuscript and the other for bibliography.

The pull request

https://github.com/SevgiAkten/pycell/commit/b8ce4a93e5420eebf218fb8ad49334985857bcfe

implements the sample manuscript.

**Comment by jbytecode** [comment]
The markdown commands are well-explained in the example:

https://joss.readthedocs.io/en/latest/example_paper.html

**Comment by jbytecode** [comment]
With the commit: https://github.com/SevgiAkten/pycellga/commit/81a8f39d4aa7306822b4ada3fc8dc625e98299ff

we can preview the pdf. Note that this tool is only for previewing issues, the JOSS rendered files look different.

**Comment by SevgiAkten** [comment]
> With the commit: [81a8f39](https://github.com/SevgiAkten/pycellga/commit/81a8f39d4aa7306822b4ada3fc8dc625e98299ff)
> 
> we can preview the pdf. Note that this tool is only for previewing issues, the JOSS rendered files look different.

Thank you, got it.

**Comment by jbytecode** [comment]
Do not think about styling

**Comment by SevgiAkten** [comment]
I think the issue is resolved.
