### ISSUE TITLE
JOSS submission guidelines

### ISSUE THREAD

**Issue by jbytecode** [SevgiAkten/pycellga#22]
- https://joss.readthedocs.io/en/latest/index.html

**Comment by jbytecode** [comment]
in JOSS, the submissions that have lines of codes of 1000 are generally subject to a scope review among reviewers.

in the current form the package has the summary below:

```
     119 text files.
     114 unique files.                                          
      73 files ignored.

github.com/AlDanial/cloc v 1.98  T=0.04 s (3189.9 files/s, 127819.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                         112            988            393           3174
Markdown                         1              3              0              5
Text                             1              2              0              3
-------------------------------------------------------------------------------
SUM:                           114            993            393           3182
-------------------------------------------------------------------------------
```

which is considered a good state.

**Comment by jbytecode** [comment]
It's strange that the latest form of the bibliography includes the entry 

```
 59 @article{karakaya2024improved,
 60   title={Improved Cellular Genetic Algorithms for Complex Optimization Problems},
 61   author={Karakaya, Sevgi Akten and Satman, Mehmet Hakan},
 62   journal={Journal of Optimization},
 63   volume={32},
 64   number={1},
 65   pages={123--145},
 66   year={2024},
 67   publisher={Elsevier}
 68 }
```

lol, and it would be good if it was real :)

**Comment by SevgiAkten** [comment]
It was a mistake, sorry. :)

**Comment by SevgiAkten** [comment]
`  161 text files.
     154 unique files.                                          
     167 files ignored.

github.com/AlDanial/cloc v 2.02  T=0.09 s (1632.8 files/s, 108816.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                         145           1663           4097           4173
Markdown                         4             55              0            101
TeX                              1              8              0             79
Text                             3              7              0             55
YAML                             1              6              0             19
-------------------------------------------------------------------------------
SUM:                           154           1739           4097           4427
-------------------------------------------------------------------------------`

**Comment by SevgiAkten** [comment]
161 text files.
     154 unique files.                                          
     167 files ignored.

github.com/AlDanial/cloc v 2.02  T=0.09 s (1632.8 files/s, 108816.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                         145           1663           4097           4173
Markdown                         4             55              0            101
TeX                              1              8              0             79
Text                             3              7              0             55
YAML                             1              6              0             19
-------------------------------------------------------------------------------
SUM:                           154           1739           4097           4427
-------------------------------------------------------------------------------

**Comment by SevgiAkten** [comment]
119 text files.
     114 unique files.                                          
      73 files ignored.

github.com/AlDanial/cloc v 1.98  T=0.04 s (3189.9 files/s, 127819.2 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                         112            988            393           3174
Markdown                         1              3              0              5
Text                             1              2              0              3
-------------------------------------------------------------------------------
SUM:                           114            993            393           3182
-------------------------------------------------------------------------------

**Comment by SevgiAkten** [comment]
Now the statement like that: 
`     161 text files.
     154 unique files.                                          
     167 files ignored.

github.com/AlDanial/cloc v 2.02  T=0.09 s (1632.8 files/s, 108816.1 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
Python                         145           1663           4097           4173
Markdown                         4             55              0            101
TeX                              1              8              0             79
Text                             3              7              0             55
YAML                             1              6              0             19
-------------------------------------------------------------------------------
SUM:                           154           1739           4097           4427
-------------------------------------------------------------------------------`
