### ISSUE TITLE
Registration of package in the PyPI

### ISSUE THREAD

**Issue by jbytecode** [SevgiAkten/pycellga#23]
The first thing is to find a new name for the package.

I suggest `pycellga`.

We have two options:

- Changing the name of the current repository
- Copying all of the contents to the new repository with the new name

After solving the issue above, we can register the package in the PyPI index:

https://pypi.org/

Here is the guidelines for registering Python packages

https://packaging.python.org/en/latest/tutorials/packaging-projects/

**Comment by jbytecode** [comment]
The other thing is we changed the repo name but the source folder is still cga.

I don't sure what happens when we register the package in pypi. 

Will user call it by typing

from cga import things 

Or

from pycellga import things

**Comment by jbytecode** [comment]
I think the automatic documentation belongs to the JOSS submission but not the package registration. 

If your tests are comprehensive enough and you are sure that the optimizers do their job properly, we can go forward with the PyPI registration stuff.

**Comment by SevgiAkten** [comment]
I have successfully completed the registration of the pycellga package. You can check it at the following link: https://pypi.org/project/pycellga/0.1.0/.

**Comment by SevgiAkten** [comment]
Latest version:
https://pypi.org/project/pycellga/0.1.2/

**Comment by jbytecode** [comment]
congratulations.

I created a virtual environment and successfully installed the package. But in a custom Python script

```python
import pycellga
```

didn't work. I can work it like this

![Screenshot from 2024-08-14 15-08-03](https://github.com/user-attachments/assets/89582713-1761-46fe-96e0-c51badebd520)


So the package can be installed by its name but it is recognized as `src` (I think this is because of the source folder name)

Could you please fix that?

**Comment by jbytecode** [comment]
```python
>>> import src.byte_operators
>>> src.byte_operators.floats_to_bits([1])
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0]
>>> src.byte_operators.floats_to_bits([-1])
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1]
```

other things seem to be work :)

**Comment by jbytecode** [comment]
Please feel free to close this issue when you get it done

**Comment by SevgiAkten** [comment]
Latest version:
https://pypi.org/project/pycellga/0.2.1/

**Comment by SevgiAkten** [comment]
<img width="1187" alt="Ekran Resmi 2024-08-14 18 25 37" src="https://github.com/user-attachments/assets/8cf1a644-311a-4c9a-ac18-943d662c2e88">
Our example works with a little bit modification on my local
