### ISSUE TITLE
Github Actions

### ISSUE THREAD

**Issue by jbytecode** [SevgiAkten/pycellga#25]
Github actions is responsible of compiling/building/testing/publishing of the code after merging a pull request or pushing a commit.

It would be better to run all of the tests after each single push.

This is called GitHub actions.

Please take a look the page:

https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

to add some GitHub actions that perform tests after commits, so we can see if we break things online.

Here is the sample GitHub action for a Python package:

https://github.com/mnets/pymnet/blob/master/.github/workflows/tests.yml

**Comment by SevgiAkten** [comment]
I think this issue is also completely resolved and I'm closing.
