### ISSUE TITLE
Automatic generation of web helps

### ISSUE THREAD

**Issue by jbytecode** [SevgiAkten/pycellga#28]
It is a common pattern to generate HTML based help systems using the code comments.

In our case we already have the code comments. 

The next step is to (and hopefully the last step) creating an automatic web based help system. This thing requires these steps

- Selecting the tool for generating HTML content (maybe pydoc?)
- Creating a Github CI action (like we did before for testing) for automatic creation of the documentation
- The Github CI should also upload the HTML content in a special area of the github repo. Go Github Repo -> Settings -> Pages, the keyword for the google search is gh-pages.
- Here is a sample for a Julia package, https://jbytecode.github.io/JMcDM/dev/, I think in our case, we will have a SevgiAkten.github.io/pycellga or something like that

finally in each single commit an action will be triggered automatically and the new documentation will be created.

**Comment by jbytecode** [comment]
By the last commit, the documentation is created in the gh-pages branch of the repo:

https://github.com/SevgiAkten/pycellga/tree/gh-pages

somehow, but the content is not hosted as a web page, is it related to the Repo -> Settings -> Pages stuff?

**Comment by SevgiAkten** [comment]
I finally managed to set up the documentation system and deploy it on GitHub Pages. It took some effort, but it's done! You can check out the documentation at this link: https://sevgiakten.github.io/pycellga/.

**Comment by jbytecode** [comment]
It seems good, congratulations!!!

I think it can be improved as some pages are not rendered properly, but it's easy to do for you!

**Comment by jbytecode** [comment]
This issue is related to the issue

https://github.com/SevgiAkten/pycellga/issues/60

so we can close this one
