### ISSUE TITLE
The optimizer design

### ISSUE THREAD

**Issue by jbytecode** [SevgiAkten/pycellga#33]
I have created a new repository today, for one of my PhD students.

The repo implements the random key genetic algorithm for permutation optimizations. Here is the repo:

https://github.com/jbytecode/randomkeyga.py

The package implements many classes and functions, however, for the user, the `optimize` function performs the whole stuff, taking the parameters to specialize the way optimizer does the things.

You said you plan to get things more tidy, the code would be useful, maybe, when you design the optimizer's arguments.

fyi.

**Comment by SevgiAkten** [comment]
I think the issue is resolved now.
