### ISSUE TITLE
Why Individuals holds the problem info

### ISSUE THREAD

**Issue by jbytecode** [SevgiAkten/pycellga#44]
I have been investigating the problem field in the individual class, but I think an Individual is responsible for holding genes, nothing else, so I tried to remove it.

The commit removes the problem information from the Individual class.

Tests are passed.

https://github.com/SevgiAkten/pycellga/commit/cfe5f3cf5ffcf9fd797eb082cd962945a243f6b0

**Comment by jbytecode** [comment]
please feel free to close this issue if you are agreed with the change.

**Comment by SevgiAkten** [comment]
Thank you! I’ve reviewed the changes and agree with them. I'll close the issue now.
