### ISSUE TITLE
Unused document files

### ISSUE THREAD

**Issue by jbytecode** [SevgiAkten/pycellga#61]
The directory 

https://github.com/SevgiAkten/pycellga/tree/main/docs/_build

has machine generated html files, but I think it should not be hosted as the source code, it is generated in CI automatically and hosted by Github. In short, it is considered trash.

Maybe, deleting this folder from the repo and adding the directory to the .gitignore is the solution, I am not sure, but in my repos the source code doesn't include the compiled HTML documentation, it should be current for the Python packages.

**Comment by SevgiAkten** [comment]
Now the repository only contains the top-level files; the HTML files have been removed.
